package com.arassec.artivact.backend.service.creator.adapter;

public enum AdapterImplementation {

    FALLBACK_BACKGROUND_REMOVAL_ADAPTER,

    REMBG_REMOTE_BACKGROUND_REMOVAL_ADAPTER,

    FALLBACK_CAMERA_ADAPTER,

    DIGI_CAM_CONTROL_CAMERA_ADAPTER,

    DIGI_CAM_CONTROL_REMOTE_CAMERA_ADAPTER,

    GPHOTO_TWO_CAMERA_ADAPTER,

    FALLBACK_TURNTABLE_ADAPTER,

    ARTIVACT_TURNTABLE_ADAPTER,

    FALLBACK_MODEL_CREATOR_ADAPTER,

    MESHROOM_MODEL_CREATOR_ADAPTER,

    METASHAPE_MODEL_CREATOR_ADAPTER,

    FALLBACK_MODEL_EDITOR_ADAPTER,

    BLENDER_MODEL_EDITOR_ADAPTER

}
