spring.jpa.open-in-view=false

spring.flyway.locations=classpath:/db/migration/av/{vendor}

# Fallback datasource, if no other is provided:
spring.datasource.url=jdbc:h2:file:./dbdata/artivact-vault;AUTO_SERVER=true
spring.datasource.username=artivact
spring.datasource.password=vault
spring.datasource.driver-class-name=org.h2.Driver

logging.level.com.arassec=INFO

artivact.vault.data.dir=Data
artivact.vault.available.locales=en,de
artivact.vault.title=Artivact-Vault
