spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=250MB

spring.flyway.locations=classpath:/db/migration/av/{vendor}

# Fallback datasource, if no other is provided:
spring.datasource.url=jdbc:h2:file:./dbdata/creatorArtivact-vault;AUTO_SERVER=true
spring.datasource.username=creatorArtivact
spring.datasource.password=vault
spring.datasource.driver-class-name=org.h2.Driver

logging.level.com.arassec=INFO

artivact.vault.available.locales=en,de
artivact.vault.title=Artivact-Vault
