package com.arassec.artivact.application.port.in.ai;

/**
 * Use case for testing AI configuration (translation and text-to-speech).
 */
public interface TestAiConfigurationUseCase {

    /**
     * Tests the translation configuration by translating the given text into the specified locale.
     *
     * @param text         The text to translate.
     * @param targetLocale The target locale for the translation.
     * @return The translated text.
     */
    String testTranslation(String text, String targetLocale);

    /**
     * Tests the text-to-speech configuration by generating an audio file from the given text.
     * The audio file is saved as 'audio-content.mp3' in the project's temp directory.
     *
     * @param text         The text to convert to audio.
     * @param targetLocale The target locale for the audio generation.
     */
    void testTts(String text, String targetLocale);

    /**
     * Loads the test audio file generated by {@link #testTts(String, String)}.
     *
     * @return The audio file content as byte array.
     */
    byte[] loadTestTtsAudio();

}
