com.arassec.artivact.creator.standalone.title=Artivact-Creator

logging.level.com.arassec=INFO
logging.level.javafx.css=ERROR

# possible values: 'ArtivactTurntable'
adapter.implementation.turntable=fallback
adapter.implementation.turntable.delay=300

# possible values: 'DigiCamControl' or 'gphoto2'
adapter.implementation.camera=fallback
adapter.implementation.camera.executable=

# possible values: 'fallback', 'RemBg' or 'RemBgRemote'
adapter.implementation.background=fallback
adapter.implementation.background.executable=

# possible values: 'Meshroom', 'Metashape'
adapter.implementation.model-creator=fallback
adapter.implementation.model-creator.executable=

# possible values: 'Blender'
adapter.implementation.model-editor=fallback
adapter.implementation.model-editor.executable=

recent-projects=
