com.arassec.artivact.creator.standalone.title=Artivact-Creator

logging.level.com.arassec=INFO

# possible values: RemBg
adapter.implementation.background=fallback
adapter.implementation.background.executable=
# possible values: DigiCamControl, gphoto2
adapter.implementation.camera=fallback
adapter.implementation.camera.executable=
# possible values: Meshroom
adapter.implementation.model-creator=fallback
adapter.implementation.model-creator.executable=
# possible values: Blender
adapter.implementation.model-editor=fallback
adapter.implementation.model-editor.executable=
# possible values: ArtivactTurntable
adapter.implementation.turntable=fallback
adapter.implementation.turntable.delay=100

recent-projects=
