name: Build

on:
  push:
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Build with Maven
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            ./mvnw.cmd clean install --no-transfer-progress
          else
            ./mvnw clean install -Pe2e -Dplaywright.deps.phase=generate-test-sources --no-transfer-progress
          fi
        shell: bash
      - name: Analyze with SonarCloud
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            ./mvnw.cmd -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=arassec_artivact --no-transfer-progress
          else
            ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=arassec_artivact --no-transfer-progress
          fi
        shell: bash

  dependabot:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@ffa630c65fa7e0ecfa0625b5ceda64399aea1b36
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a Dependabot PR
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh pr review --approve "$PR_URL"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.dependency-type != 'github_actions' || !contains(steps.metadata.outputs.updated-dependency-names, 'actions/') }}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --merge "$PR_URL"
