name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:

  release-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Build
        run: ./mvnw clean install -Drevision=$RELEASE_VERSION --no-transfer-progress
      - name: Copy Artivact-Server jar (add 'v' to version)
        run: cp artivact-server/target/artivact-server-${{ env.RELEASE_VERSION }}.jar artivact-server/target/artivact-server-v${{ env.RELEASE_VERSION }}.jar
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: "artivact-server/target/artivact-server-v${{ env.RELEASE_VERSION }}.jar"
          release_name: 'Version ${{ env.RELEASE_VERSION }}'
          tag: ${{ github.ref }}
          overwrite: true
