name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:

  release-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Build
        run: ./mvnw clean install -Drevision=$RELEASE_VERSION --no-transfer-progress
      - name: Copy Artivact-Server jar (add 'v' to version)
        run: cp artivact-server/target/artivact-server-${{ env.RELEASE_VERSION }}.jar artivact-server/target/artivact-server-v${{ env.RELEASE_VERSION }}.jar
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: "artivact-server/target/artivact-server-v${{ env.RELEASE_VERSION }}.jar"
          release_name: 'Version ${{ env.RELEASE_VERSION }}'
          tag: ${{ github.ref }}
          overwrite: true

  release-desktop-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
      - name: Get release info
        id: release_info
        uses: revam/gh-action-get-tag-and-version@v1
        with:
          tag: ${{ github.ref }}
          prefix: v
          prefixRegex: "[vV]?"
      - name: Debug
        run: echo 'version = ${{ steps.release_info.outputs.version_short }}'
      - name: Build
        run: .\mvnw.cmd clean install -Drevision="${{ steps.release_info.outputs.version_short }}" --no-transfer-progress -P release-desktop-windows
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: "artivact-desktop/target/artivact-desktop-windows-v${{ steps.release_info.outputs.version_short }}-bin.zip"
          release_name: 'Version ${{ steps.release_info.outputs.version_short }}'
          tag: ${{ github.ref }}
          overwrite: true

  release-desktop-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Build
        run: ./mvnw clean install -Drevision=$RELEASE_VERSION --no-transfer-progress -P release-desktop-linux
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: "artivact-desktop/target/artivact-desktop-linux-v${{ env.RELEASE_VERSION }}-bin.tar.gz"
          release_name: 'Version ${{ env.RELEASE_VERSION }}'
          tag: ${{ github.ref }}
          overwrite: true
